### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by danhealy** [HipByte/motion-fabric#7]
After following the install instructions, I receive a NameError when the app gets to this line:

`Fabric.with([Crashlytics])`

```
*** Terminating app due to uncaught exception 'NameError', reason: 'app_delegate.rb:13:in `application:didFinishLaunchingWithOptions:': uninitialized constant AppDelegate::Fabric (NameError)
```

I believe this is because the bridgesupport file isn't being generated / can't be found, I also receive this warning:

`WARNING! Could not find .bridgesupport file for framework "Fabric".`

Looking at the code, it's looking only for the iOS version:

https://github.com/HipByte/motion-fabric/blob/master/lib/motion-fabric.rb#L102

However, adding a similar line to my rakefile manually doesn't seem to help:

`app.framework_search_paths << './vendor/Pods/Fabric/tvOS'`

That path `/vendor/Pods/Fabric/tvOS` does exist and contains `Fabric.framework`.

I'm seeing the same exact issue with the Crittercism gem, it can't find the bridgesupport file and crashes with a NameError when I try to use `Crittercism` in the app delegate.  I think either I'm missing something obvious or it's a rubymotion / motion-cocoapods issue.  At any rate, the hard coded path for iOS should be updated here.

**Comment by MarkVillacampa** [comment]
This was an issue in motion-cocoapods fixed by this commit https://github.com/HipByte/motion-cocoapods/commit/6420c8cbfa6532a7d776c54a744294e7580e01f5

Additionally, I added the corresponding search paths for motion-fabric here: https://github.com/HipByte/motion-fabric/commit/d8f317a53f8bdb9d175a2308659ada949cea8e51

I've just released motion-fabric 0.7 and motion-cocoapods 1.8.1 which should solve the issue. you simply have to "bundle update" :)
